"""Terraform import command generator."""

from app.models.resources import DiscoveredResource


class ImportGenerator:
    """Generates terraform import commands for discovered resources."""

    def generate(self, resources: list[DiscoveredResource]) -> str:
        """Generate a bash script with terraform import commands.

        Args:
            resources: List of discovered resources.

        Returns:
            Shell script content with import commands.
        """
        lines = [
            "#!/bin/bash",
            "# Generated by Terramorph - Reverse Terraform",
            "# Run this script after 'terraform init' to import existing resources",
            "",
            "set -e",
            "",
            'echo "Starting Terraform import..."',
            "",
        ]

        for resource in resources:
            terraform_addr = (
                f"{resource.terraform_resource_type}.{resource.terraform_resource_name}"
            )
            lines.append(
                f'echo "Importing {resource.name} ({resource.type.value})..."'
            )
            lines.append(
                f"terraform import {terraform_addr} {resource.terraform_import_id}"
            )
            lines.append("")

        lines.append('echo ""')
        lines.append(f'echo "Successfully imported {len(resources)} resources."')
        lines.append('echo "Run \\"terraform plan\\" to verify the state matches your infrastructure."')

        return "\n".join(lines)
