"""Terraform import block generator.

Generates import blocks in .tf format (Terraform 1.5+) instead of shell scripts.
See: https://developer.hashicorp.com/terraform/language/import
"""

from app.models.resources import DiscoveredResource


class ImportGenerator:
    """Generates terraform import blocks in .tf format."""

    def generate(self, resources: list[DiscoveredResource]) -> str:
        """Generate import.tf with import blocks for all resources.

        Uses the Terraform 1.5+ native import block syntax:
            import {
              to = google_compute_instance.my_vm
              id = "projects/my-project/zones/us-central1-a/instances/my-vm"
            }

        Args:
            resources: List of discovered resources.

        Returns:
            Content for import.tf file.
        """
        lines = [
            "# Generated by Terramorph - Reverse Terraform",
            "# Terraform 1.5+ native import blocks",
            "# Run 'terraform plan' to preview the import, then 'terraform apply' to execute.",
            "",
        ]

        for resource in resources:
            terraform_addr = (
                f"{resource.terraform_resource_type}.{resource.terraform_resource_name}"
            )
            lines.append(f"# {resource.name} ({resource.type.value})")
            lines.append("import {")
            lines.append(f'  to = {terraform_addr}')
            lines.append(f'  id = "{resource.terraform_import_id}"')
            lines.append("}")
            lines.append("")

        lines.append(
            f"# Total: {len(resources)} resources to import"
        )
        lines.append(
            '# After import, run "terraform plan" to verify state matches infrastructure.'
        )

        return "\n".join(lines)

    def generate_shell(self, resources: list[DiscoveredResource]) -> str:
        """Generate a legacy shell script with terraform import commands.

        Kept for backward compatibility.

        Args:
            resources: List of discovered resources.

        Returns:
            Shell script content with import commands.
        """
        lines = [
            "#!/bin/bash",
            "# Generated by Terramorph - Reverse Terraform",
            "# Legacy import script — consider using import.tf blocks instead (Terraform 1.5+)",
            "",
            "set -e",
            "",
            'echo "Starting Terraform import..."',
            "",
        ]

        for resource in resources:
            terraform_addr = (
                f"{resource.terraform_resource_type}.{resource.terraform_resource_name}"
            )
            lines.append(
                f'echo "Importing {resource.name} ({resource.type.value})..."'
            )
            lines.append(
                f"terraform import {terraform_addr} {resource.terraform_import_id}"
            )
            lines.append("")

        lines.append('echo ""')
        lines.append(f'echo "Successfully imported {len(resources)} resources."')
        lines.append(
            'echo "Run \\"terraform plan\\" to verify the state matches your infrastructure."'
        )

        return "\n".join(lines)
